<a href="https://colab.research.google.com/github/atikhasan007/Machine-Learning/blob/main/News%20Article%20Recommendation%20System/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Financial News Article Recommendation System**

**Dataset Link **
https://www.kaggle.com/datasets/noorsaeed/mind-small-cleaned-dataset

In [17]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("noorsaeed/mind-small-cleaned-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'mind-small-cleaned-dataset' dataset.
Path to dataset files: /kaggle/input/mind-small-cleaned-dataset


**Build 3 recommendation strategies:**

Content-Based Filtering
collaborative Filtering
hybrid Recommendation
Return a personalized feed based on user history (like tiktok/reels.)
prototype in jupyter notebook first then will will move to flask app.py based backend

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [19]:
df = pd.read_csv("/root/.cache/kagglehub/datasets/noorsaeed/mind-small-cleaned-dataset/versions/1/merged_df.csv")

In [20]:
df.head()

news_id category               subcategory  \
0  N37243  finance       finance-real-estate   
1  N25540  finance  finance-saving-investing   
2  N37129  finance             finance-taxes   
3  N36064  finance         finance-companies   
4  N63006  finance         finance-savemoney   

                                               title  \
0  the 25 most desirable places to live in the us...   
1  take heart millennials investing is within you...   
2  don t be like these celebrities convicted of t...   
3  more store closings coming the list of retaile...   
4   17 surprising ways penny pinching costs you more   

                                            abstract  \
0  check out where u s residents would live if th...   
1  news headlines might lead you to believe that ...   
2     these celebs were in hot water with the taxman   
3  more than 10 months into 2019 more than 8 600 ...   
4  frugal living could end up costing you in the ...   

                                             url  \
0  https://assets.msn.com/labs/mind/AABvlID.html   
1  https://assets.msn.com/labs/mind/AAEmGBr.html   
2  https://assets.msn.com/labs/mind/AAEGGF9.html   
3  https://assets.msn.com/labs/mind/AADN84N.html   
4  https://assets.msn.com/labs/mind/AAB4M2y.html   

                                      title_entities  \
0                                                 []   
1                                                 []   
2  [{"Label": "Tax evasion", "Type": "C", "Wikida...   
3                                                 []   
4                                                 []   

                                   abstract_entities  user_id  clicked  \
0  [{"Label": "United States", "Type": "G", "Wiki...  unknown      1.0   
1                                                 []  unknown      1.0   
2                                                 []   U73032      0.0   
3                                                 []  unknown      1.0   
4                                                 []   U67894      0.0   

                                             content  
0  the 25 most desirable places to live in the us...  
1  take heart millennials investing is within you...  
2  don t be like these celebrities convicted of t...  
3  more store closings coming the list of retaile...  
4  17 surprising ways penny pinching costs you mo...

In [21]:
df['content'] = df['title'] +" "+ df['abstract'] + " " + df['category']

In [22]:
df['content'].head()

0    the 25 most desirable places to live in the us...
1    take heart millennials investing is within you...
2    don t be like these celebrities convicted of t...
3    more store closings coming the list of retaile...
4    17 surprising ways penny pinching costs you mo...
Name: content, dtype: object

**Content Based Recommendation  System**

In [23]:
#Tf-IDF vectorization
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Fill missing values with empty strings
df['content'] = df['content'].fillna('')

vectorizer = TfidfVectorizer(stop_words='english', max_df=0.8, min_df=5, ngram_range=(1,2))
tfidf_matrix = vectorizer.fit_transform(df['content'])
# tfidf_matrix.array()
tfidf_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [24]:
#cosine similarity matrix

cosine_sim = cosine_similarity(tfidf_matrix,tfidf_matrix);
cosine_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

**Recommendatin Function**

In [30]:
import re
title = "top investemnt #$%$%$%^&& strateginekmon 300"
title = re.sub(r'[^\w\s]', '', title)
title = title.lower().strip()


title_vec = vectorizer.transform([title])
title_vec.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [34]:
cosine_scores  = cosine_similarity(title_vec, tfidf_matrix).flatten()
cosine_scores

array([0., 0., 0., ..., 0., 0., 0.])

In [40]:
indices = cosine_scores.argsort()[::-1][:5]
df.loc[indices,['news_id','title','category','url']]

news_id                                              title category  \
1269  N25074  alibaba group thwarts 300 million hack attempt...  finance   
1666  N64178         how to halt global warming for 300 billion  finance   
1091   N1200  exxon profit plummets with plenty of oil to go...  finance   
497    N5999  europe s defense spending nears 300 billion as...  finance   
785   N53988  millions more people at risk of climate relate...  finance   

                                                url  
1269  https://assets.msn.com/labs/mind/AAIPW9R.html  
1666  https://assets.msn.com/labs/mind/AAJdjSR.html  
1091  https://assets.msn.com/labs/mind/AAJG5RS.html  
497   https://assets.msn.com/labs/mind/AAJF0CH.html  
785   https://assets.msn.com/labs/mind/AAJy6zi.html

In [42]:
##Recomendation function

def content_base_rec(title, top_n=5):
    # cleaning
    title = re.sub(r'\W+', ' ', title)  # Remove special chars
    title = title.lower().strip()

    # Vectorize input title
    title_vec = vectorizer.transform([title])

    # Compute cosine similarity
    sim_scores = cosine_similarity(title_vec, tfidf_matrix).flatten()

    # Get top N indices
    top_indices = sim_scores.argsort()[::-1][:top_n]

    return df.loc[top_indices, ['news_id', 'title', 'category', 'subcategory', 'url', 'abstract']]


content_base_rec("Top investment strategies in 2025")

news_id                                              title category  \
2841  N35029     china s hottest investment overpriced sneakers  finance   
1222   N3461         5 medium risk investments for high returns  finance   
2736   N8988  shoppers share black friday strategies that ac...  finance   
1810  N15796  ubs tightens investment banking belt as earnin...  finance   
1570  N25302  the main reason billionaires move has nothing ...  finance   

                   subcategory                                            url  \
2841                   markets  https://assets.msn.com/labs/mind/BBWwqU4.html   
1222  finance-saving-investing  https://assets.msn.com/labs/mind/AAJXp3M.html   
2736         finance-savemoney  https://assets.msn.com/labs/mind/BBWqXL6.html   
1810         finance-companies  https://assets.msn.com/labs/mind/AAJ9Rzi.html   
1570       finance-real-estate  https://assets.msn.com/labs/mind/AAJa8Vj.html   

                                               abstract  
2841  forget stocks real estate even cryptocurrencie...  
1222  a few high return investing strategies that co...  
2736  if at first you don t succeed talk to someone ...  
1810  ubs tightens investment banking belt as earnin...  
1570  middle class americans can learn some financia...

**Collaborative Filtering (Use-Based or Implicit)**

In [43]:
from sklearn.preprocessing import LabelEncoder

#Encode user_id and news_id to numeric
user_encoder = LabelEncoder()
news_encoder = LabelEncoder()
df['user_id_encoded'] = user_encoder.fit_transform(df['user_id'])
df['news_id_encoded'] = news_encoder.fit_transform(df['news_id'])



In [46]:
#create user-item matrix (rows=user, cols=nws,values=clicked)
user_item_matrix = df.pivot_table(index='user_id_encoded',columns='news_id_encoded',values='clicked',fill_value=0)

user_similarity = cosine_similarity(user_item_matrix)


In [47]:
user_similarity

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

**Recommendation function**

In [49]:
def collaborative_base_rec(input_user, df, top_k=5):
    # Encode user_id to index
    user_idx = user_encoder.transform([input_user])[0]

    # Get similarity scores for this user with others
    sim_scores = user_similarity[user_idx]

    # Get clicked items by this user
    user_clicks = user_item_matrix.iloc[user_idx]

    # Calculate weighted sum of clicks by similarity scores
    weighted_scores = sim_scores @ user_item_matrix.values

    # Remove already clicked items from recommendations
    weighted_scores[user_clicks == 1] = 0

    # Get top news indices based on scores
    top_news_indices = weighted_scores.argsort()[::-1][:top_k]

    # Decode back to news_ids
    recommended_news_ids = news_encoder.inverse_transform(top_news_indices)

    # Filter original df for those news and drop duplicates
    recommended_news = df[df['news_id'].isin(recommended_news_ids)][
        ['news_id', 'title', 'category', 'subcategory', 'url', 'abstract']
    ].drop_duplicates(subset='news_id')

    return recommended_news.reset_index(drop=True)

recommendations = collaborative_base_rec(
    input_user='U91836',
    df=df,
)

recommendations

news_id                                              title category  \
0   N1037  ceo departures hit a new high in october on pa...  finance   
1   N9988  everybody is calling twin snow storms mean goo...  finance   
2   N1039  supreme court rejects charter appeal of sprint...  finance   
3   N1004  small business lessons from blue collar millio...  finance   
4   N9989  how should billionaires spend their money to f...  finance   

              subcategory                                            url  \
0       finance-companies  https://assets.msn.com/labs/mind/AAJWqVs.html   
1             financenews  https://assets.msn.com/labs/mind/AAJytd9.html   
2       finance-companies  https://assets.msn.com/labs/mind/AAJOpA2.html   
3  finance-small-business  https://assets.msn.com/labs/mind/BBWpEsR.html   
4                 markets  https://assets.msn.com/labs/mind/BBWE4pA.html   

                                            abstract  
0  october marked the highest month on record wit...  
1  with slick snowy roads leading to a lot of sli...  
2  usa court charter commns sprint corp update 1 ...  
3                   not all millionaires wear a suit  
4  is it better to invest in developing clean ene...

**3 Hybrid Recommendation system**

In [51]:


def hybrid_recommendations(user_id,title, df,top_n=5):
    # clean title
    title = re.sub(r'\W+', ' ', title)  # Remove special chars
    title = title.lower().strip()


    # Get content-based recommendations
    content_recs = content_base_rec(title)

    # Get collaborative-based recommendations
    collab_recs = collaborative_base_rec(user_id, df)

    # Merge the recommendations
    combined_recs = pd.concat([content_recs, collab_recs]).drop_duplicates().reset_index(drop=True)

    # Limit the number of recommendations to the top 'n'
    combined_recs = combined_recs.head(top_n)

    return combined_recs

hybrid_recommendations(
    user_id='U91836',
    title="The 1 reason you shouldn’t hesitate to claim Social Security",
    df=df,
)



news_id                                              title category  \
0  N36226  the 1 reason you shouldn t hesitate to claim s...  finance   
1  N17087  the one reason to claim social security at 62 ...  finance   
2   N9751          11 social security mistakes you can avoid  finance   
3  N11593   what millennials get wrong about social security  finance   
4  N63702         will you get what social security promises  finance   

          subcategory                                            url  \
0  finance-retirement  https://assets.msn.com/labs/mind/BBWKwml.html   
1  finance-retirement  https://assets.msn.com/labs/mind/AAJJ7Jo.html   
2  finance-retirement  https://assets.msn.com/labs/mind/BBV0eGF.html   
3  finance-billstopay  https://assets.msn.com/labs/mind/AAGb1aa.html   
4  finance-retirement  https://assets.msn.com/labs/mind/AAJjqg8.html   

                                            abstract  
0  seniors are often told to wait on social secur...  
1  should you claim early if you don t really nee...  
2  social security s complicated but it s worth t...  
3  few issues unite millennials like the future o...  
4  the social security administration will happil...